ARG OS_VERSION=3.18
ARG MARCH=native

FROM alpine:$OS_VERSION

ENV CONFIG="configs/iq_collection.conf"
ENV DEBIAN_FRONTEND=noninteractive

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk update

RUN apk add --no-cache \
    cmake \
    make \
    gcc \
    g++ \
    pkgconf \
    boost-dev \
    uhd \
    uhd-dev \
    yaml-cpp-dev

COPY . /app

WORKDIR /app

RUN mkdir -p build && rm -rf build/*

WORKDIR /app/build

RUN cmake ../ && \
    make -j$(nproc) && \
    make install

WORKDIR /app

CMD [ "sh", "-c", "/usr/local/bin/uuagent \"${CONFIG}\"" ]
