FROM ghcr.io/oran-testing/components_base

WORKDIR /uuagent

COPY . .

RUN mkdir -p build && rm -rf build/*

WORKDIR /uuagent/build

RUN cmake ../ && \
    make -j$(nproc) && \
    make install

CMD [ "sh", "-c", "/usr/local/bin/uuagent /uu-agent.conf" ]
