name: Build and Publish UU Agent Docker Package

on:
  push:
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.commit-check.outputs.should_run }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Commit Message
        id: commit-check
        run: |
          if git log -1 --pretty=%B | grep -q "deploy-docker"; then
            echo "should_run=true" >> $GITHUB_ENV
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_ENV
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: check-commit
    if: needs.check-commit.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/uu-agent:latest . -f Dockerfile.alpine

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/uu-agent:latest
